### ISSUE TITLE
error?

### ISSUE THREAD

**Issue by liamxg** [ndwhelan/Nucleotide-Codon-Position-Parser#1]
<img width="866" alt="image" src="https://user-images.githubusercontent.com/46078579/227775434-6329a336-ff02-418c-867c-4647068277cb.png">

**Comment by liamxg** [comment]
@ndwhelan

**Comment by ndwhelan** [comment]
It's not a jar file, you have to compile it.

**Comment by liamxg** [comment]
@ndwhelan could you please tell me how to compile it, thanks.

**Comment by ndwhelan** [comment]
Hi. There was actually an issue - I guess I renamed the class but not the file or vice versa at some point.

I've updated the README with details on how to compile and run. If you have a JDK downloaded, it should be just those two commands. You'll need to fetch and pull the update locally. 

If you don't have a JDK downloaded, I would recommend [Open JDK](https://openjdk.org/). If you can execute `javac` on your command line, you have a JDK. This is different than a Java Runtime Environment (JRE), which would not include the compiler.

If I was creating a new proper project, I'd use Gradle or something to make this easier, but, simply put, I do not have the time to do that for the foreseeable future.

**Comment by liamxg** [comment]
@ndwhelan, thanks, I run it perfect now.
